#nullable enable
using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace CK.Poco.Immutable.Generator;

[Generator( LanguageNames.CSharp )]
public class ImmutablePocoGenerator : IIncrementalGenerator
{
    public void Initialize( IncrementalGeneratorInitializationContext context )
    {
        // Step 1: Syntax filter — keep only interface declarations that have base types.
        var pocoInterfaces = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static ( node, _ ) => node is InterfaceDeclarationSyntax iface && iface.BaseList is { Types.Count: > 0 },
            transform: static ( ctx, ct ) => GetPocoInfo( ctx, ct )
        ).Where( static info => info is not null );

        // Step 2: Register source output for each detected IPoco interface.
        context.RegisterSourceOutput( pocoInterfaces, static ( spc, info ) =>
        {
            if( info is null ) return;
            spc.AddSource( info.Value.ImmutableName + ".g.cs", GenerateImmutableSource( info.Value ) );
            spc.AddSource( info.Value.OriginalName + ".ToImmutable.g.cs", GenerateToImmutablePartial( info.Value ) );
        } );
    }

    static PocoInfo? GetPocoInfo( GeneratorSyntaxContext ctx, CancellationToken ct )
    {
        var syntax = (InterfaceDeclarationSyntax)ctx.Node;
        var symbol = ctx.SemanticModel.GetDeclaredSymbol( syntax, ct );
        if( symbol is null ) return null;

        // Resolve well-known symbols from the compilation.
        var wellKnown = WellKnownSymbols.TryCreate( ctx.SemanticModel.Compilation );
        if( wellKnown is null ) return null;
        var wk = wellKnown.Value;

        // Check if this interface implements CK.Core.IPoco (directly or transitively).
        if( !TypeMapper.IsIPoco( symbol, wk ) ) return null;

        // Collect declared properties.
        var properties = ImmutableArray.CreateBuilder<PropertyInfo>();
        foreach( var member in symbol.GetMembers() )
        {
            if( member is IPropertySymbol prop )
            {
                var typeName = TypeMapper.MapType( prop.Type, wk );
                properties.Add( new PropertyInfo( prop.Name, typeName ) );
            }
        }

        // Naming: IFoo -> IImmutableFoo (drop leading I, prepend IImmutable).
        var immutableName = TypeMapper.GetImmutableName( symbol.Name );

        var ns = symbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : symbol.ContainingNamespace.ToDisplayString();

        // Detect direct base interfaces that are also IPoco derivatives.
        // Look at direct bases (Interfaces), not AllInterfaces.
        var baseImmutableTypes = ImmutableArray.CreateBuilder<string>();
        foreach( var directBase in symbol.Interfaces )
        {
            // Skip IPoco itself — we only want derived IPoco interfaces.
            if( SymbolEqualityComparer.Default.Equals( directBase, wk.IPoco ) ) continue;

            if( TypeMapper.IsIPoco( directBase, wk ) )
            {
                // Compute the immutable name for this base interface.
                var baseImmutableName = TypeMapper.GetImmutableName( directBase.Name );

                var baseNs = directBase.ContainingNamespace.IsGlobalNamespace
                    ? null
                    : directBase.ContainingNamespace.ToDisplayString();

                baseImmutableTypes.Add( baseNs != null
                    ? baseNs + "." + baseImmutableName
                    : baseImmutableName );
            }
        }

        return new PocoInfo( symbol.Name, immutableName, ns, properties.ToImmutable(), baseImmutableTypes.ToImmutable() );
    }

    static string GenerateImmutableSource( PocoInfo info )
    {
        var sb = new StringBuilder();
        sb.AppendLine( "// <auto-generated/>" );

        if( info.Namespace != null )
        {
            sb.AppendLine();
            sb.Append( "namespace " );
            sb.Append( info.Namespace );
            sb.AppendLine( ";" );
        }

        sb.AppendLine();
        sb.Append( "public interface " );
        sb.Append( info.ImmutableName );
        sb.Append( " : " );
        if( info.BaseImmutableTypes.Length == 0 )
        {
            sb.AppendLine( "CK.Core.IImmutablePoco" );
        }
        else
        {
            for( int i = 0; i < info.BaseImmutableTypes.Length; i++ )
            {
                if( i > 0 ) sb.Append( ", " );
                sb.Append( info.BaseImmutableTypes[i] );
            }
            sb.AppendLine();
        }
        sb.AppendLine( "{" );

        foreach( var prop in info.Properties )
        {
            sb.Append( "    " );
            sb.Append( prop.TypeDisplayName );
            sb.Append( ' ' );
            sb.Append( prop.Name );
            sb.AppendLine( " { get; }" );
        }

        sb.Append( "    new " );
        sb.Append( info.OriginalName );
        sb.AppendLine( " ToMutable();" );

        sb.AppendLine( "}" );
        return sb.ToString();
    }

    static string GenerateToImmutablePartial( PocoInfo info )
    {
        var sb = new StringBuilder();
        sb.AppendLine( "// <auto-generated/>" );

        if( info.Namespace != null )
        {
            sb.AppendLine();
            sb.Append( "namespace " );
            sb.Append( info.Namespace );
            sb.AppendLine( ";" );
        }

        sb.AppendLine();
        sb.Append( "public partial interface " );
        sb.AppendLine( info.OriginalName );
        sb.AppendLine( "{" );
        sb.Append( "    new " );
        sb.Append( info.ImmutableName );
        sb.AppendLine( " ToImmutable();" );
        sb.AppendLine( "}" );
        return sb.ToString();
    }

    readonly struct PocoInfo : IEquatable<PocoInfo>
    {
        public readonly string OriginalName;
        public readonly string ImmutableName;
        public readonly string? Namespace;
        public readonly ImmutableArray<PropertyInfo> Properties;
        public readonly ImmutableArray<string> BaseImmutableTypes;

        public PocoInfo( string originalName, string immutableName, string? ns, ImmutableArray<PropertyInfo> properties, ImmutableArray<string> baseImmutableTypes )
        {
            OriginalName = originalName;
            ImmutableName = immutableName;
            Namespace = ns;
            Properties = properties;
            BaseImmutableTypes = baseImmutableTypes;
        }

        public bool Equals( PocoInfo other )
            => OriginalName == other.OriginalName
            && ImmutableName == other.ImmutableName
            && Namespace == other.Namespace
            && BaseImmutableTypes.SequenceEqual( other.BaseImmutableTypes )
            && Properties.SequenceEqual( other.Properties );

        public override bool Equals( object? obj ) => obj is PocoInfo other && Equals( other );
        public override int GetHashCode() => (ImmutableName?.GetHashCode() ?? 0) ^ BaseImmutableTypes.Length;
    }

    readonly struct PropertyInfo : IEquatable<PropertyInfo>
    {
        public readonly string Name;
        public readonly string TypeDisplayName;

        public PropertyInfo( string name, string typeDisplayName )
        {
            Name = name;
            TypeDisplayName = typeDisplayName;
        }

        public bool Equals( PropertyInfo other )
            => Name == other.Name && TypeDisplayName == other.TypeDisplayName;

        public override bool Equals( object? obj ) => obj is PropertyInfo other && Equals( other );
        public override int GetHashCode() => Name?.GetHashCode() ?? 0;
    }
}
